[[main]]
  identifier = "docs"
  name = "Documentation"
  url = "docs"
  weight = 1

[[main]]
  identifier = "updates"
  name = "Updates"
  url = "updates"
  weight = 2

[[main]]
  identifier = "blog"
  name = "Blog"
  url = "blog"
  weight = 3

[[main]]
  identifier = "contact"
  name = "Contact"
  url = "contact"
  weight = 4