---
baseURL: https://via.makerviet.org/
title: VIA - Vietnam Autonomous
theme: hugo-geekdoc
pygmentsUseClasses: true
pygmentsCodeFences: true
timeout: 180000

# Geekdoc configuration
disablePathToLower: true
enableGitInfo: true

# Needed for mermaid shortcodes
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1
    endLevel: 9

params:
  geekdocToC: 3

  geekdocRepo: https://github.com/makerhanoi/via-docs
  geekdocEditPath: edit/master/content

  geekdocSearch: true
  geekdocSearchShowParent: true